#!/usr/bin/env bash
# Reference solution for dynamo/reproducible-release-bundle.
#
# Makes the release bundle bit-identical for any rebuilder, by removing every
# way the build lets its surroundings into the artifact. Ten of them, in the
# three files that constitute the build definition.
#
# The one that decides everything else: the build must derive its notion of
# "now" from something in the tree -- the changelog's release date -- instead of
# from the clock. SOURCE_DATE_EPOCH is that value, exported so the compiler
# picks it up for __DATE__ and __TIME__, and reused for the header, the archive
# timestamps and the gzip stream.
set -euo pipefail
cd /app

# --- the build definition -----------------------------------------------
cat > Makefile <<'MAKEFILE'
# greet -- build and package the release bundle.
#
#   make            build everything and package dist/greet-$(VERSION).tar.gz
#   make check      run the binary once as a smoke test
#   make clean      remove build/, stage/ and dist/
#
# The bundle is reproducible: the same source produces the same bytes on any
# machine, at any time, under any locale, umask or account. Everything below
# marked "reproducibility" exists for that and should not be removed.

VERSION  := $(shell cat VERSION)
PREFIX   := greet-$(VERSION)

# reproducibility: the build's notion of "now" comes from the changelog, never
# from the clock. Exported so the compiler uses it for __DATE__ and __TIME__.
RELEASE_DATE := $(shell grep -m1 -o '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' CHANGELOG.md)
SOURCE_DATE_EPOCH := $(shell date -u -d '$(RELEASE_DATE) 00:00:00' +%s)
export SOURCE_DATE_EPOCH

CC       ?= cc
# reproducibility: -ffile-prefix-map keeps the absolute build directory out of
# the debug info and out of __FILE__.
CFLAGS   := -O2 -g -Wall -Wextra -Isrc -ffile-prefix-map=$(CURDIR)=.

BUILD    := build
STAGE    := stage
DIST     := dist
LIBOBJS  := $(BUILD)/greet.o $(BUILD)/util.o

.PHONY: all check clean
all: $(DIST)/$(PREFIX).tar.gz

src/buildinfo.h: tools/gen-buildinfo.sh VERSION CHANGELOG.md
	sh tools/gen-buildinfo.sh > $@

$(BUILD)/%.o: src/%.c src/greet.h src/buildinfo.h
	mkdir -p $(BUILD)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/libgreet.a: $(LIBOBJS)
	ar rcs $@ $(LIBOBJS)

$(BUILD)/greet: src/main.c src/greet.h src/buildinfo.h $(BUILD)/libgreet.a
	$(CC) $(CFLAGS) src/main.c $(BUILD)/libgreet.a -o $@

# Lay the bundle out the way it installs: bin, lib, include, share.
$(STAGE)/$(PREFIX): $(BUILD)/greet $(BUILD)/libgreet.a
	rm -rf $@
	mkdir -p $@/bin $@/lib $@/include $@/share/docs
	cp $(BUILD)/greet $@/bin/greet
	cp $(BUILD)/libgreet.a $@/lib/libgreet.a
	cp src/greet.h $@/include/greet.h
	cp docs/* $@/share/docs/
	cp VERSION CHANGELOG.md $@/
	sh tools/gen-manifest.sh $@ > $@/share/manifest.txt

# reproducibility: fixed member order, fixed timestamps, no ownership from the
# building account, permission bits independent of the caller's umask, and a
# gzip stream carrying neither the input filename nor its mtime.
$(DIST)/$(PREFIX).tar.gz: $(STAGE)/$(PREFIX)
	mkdir -p $(DIST)
	rm -f $(DIST)/$(PREFIX).tar $(DIST)/$(PREFIX).tar.gz
	cd $(STAGE) && find $(PREFIX) | LC_ALL=C sort | \
		tar cf ../$(DIST)/$(PREFIX).tar --no-recursion -T - \
		    --mtime=@$(SOURCE_DATE_EPOCH) \
		    --owner=0 --group=0 --numeric-owner \
		    --mode=go-w
	gzip -n -9 $(DIST)/$(PREFIX).tar

check: $(BUILD)/greet
	./$(BUILD)/greet --version
	./$(BUILD)/greet Ada
	./$(BUILD)/greet --upper Ada

clean:
	rm -rf $(BUILD) $(STAGE) $(DIST) src/buildinfo.h
MAKEFILE

# --- the generated header ------------------------------------------------
cat > tools/gen-buildinfo.sh <<'BUILDINFO'
#!/bin/sh
# Emit the build-information header the CLI reports through --version and
# --buildinfo. Run from the top of the source tree.
#
# Every value here is derived from the tree, never from the machine: the date
# comes from SOURCE_DATE_EPOCH, and the account and host are fixed strings. A
# release must not record who built it or where, or two builds of the same
# source disagree.
set -eu

: "${SOURCE_DATE_EPOCH:=0}"

echo '/* Generated by tools/gen-buildinfo.sh -- do not edit. */'
echo '#ifndef BUILDINFO_H'
echo '#define BUILDINFO_H'
echo "#define BUILD_DATE \"$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d)\""
echo '#define BUILD_USER "reproducible"'
echo '#define BUILD_HOST "reproducible"'
echo '#endif'
BUILDINFO

# --- the manifest ---------------------------------------------------------
cat > tools/gen-manifest.sh <<'MANIFEST'
#!/bin/sh
# List every packaged file with its size, one per line, for share/manifest.txt.
# Takes the staging root as its only argument.
#
# The sort is pinned to the C locale: under any other collation the same set of
# names comes out in a different order and the manifest -- and therefore the
# bundle -- changes.
set -eu
root="$1"

cd "$root"
find . -type f ! -name manifest.txt | sed 's|^\./||' | LC_ALL=C sort |
while read -r f; do
    printf '%s %s\n' "$(wc -c < "$f" | tr -d ' ')" "$f"
done
MANIFEST

chmod +x tools/gen-buildinfo.sh tools/gen-manifest.sh
