#!/bin/sh
# Emit the build-information header the CLI reports through --version and
# --buildinfo. Run from the top of the source tree.
set -eu

echo '/* Generated by tools/gen-buildinfo.sh -- do not edit. */'
echo '#ifndef BUILDINFO_H'
echo '#define BUILDINFO_H'
echo "#define BUILD_DATE \"$(date +%Y-%m-%d)\""
echo "#define BUILD_USER \"${USER:-$(id -un)}\""
echo "#define BUILD_HOST \"$(hostname)\""
echo '#endif'
